Natura/Controllers/InventarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Natura.Data;
using Natura.ViewModels;

namespace Natura.Controllers
{
    public class InventarioController : Controller
    {
        private Context db = new Context();
        // GET: Inventario
        public ActionResult Index()
        {
            return View(new InventarioViewModel {
                IdProducto = 1,
                Nombre = "Perro"
            });
         }
    }
}

Natura/Controllers/ProductoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Natura.Data;
using Natura.Models;
using Natura.ViewModels;

namespace Natura.Controllers
{
    public class ProductoesController : Controller
    {
        private Context db = new Context();

        // GET: Productoes
        public ActionResult Index()
        {
            var productos = db.Productos.Include(p => p.Categoria).Include(p => p.Linea);
            return View(productos.ToList());
        }

        // GET: Productoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Productos.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            Categoria categoria = db.Categorias.Find(producto.IdCategoria);
            Linea linea = db.Lineas.Find(producto.IdLinea);

            return View(new ProductoViewModel()
            {
                IdProducto = producto.IdProducto,
                Nombre = producto.Nombre,
                Codigo = producto.Codigo,
                NombreCategoria = categoria.Nombre,
                NombreLinea = linea.Nombre
            });
            
        }

        // GET: Productoes/Create
        public ActionResult Create()
        {
            ViewBag.IdCategoria = new SelectList(db.Categorias, "IdCategoria", "Nombre");
            ViewBag.IdLinea = new SelectList(db.Lineas, "IdLinea", "Nombre");
            return View();
        }

        // POST: Productoes/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdProducto,Nombre,Codigo,IdCategoria,IdLinea")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                db.Productos.Add(producto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdCategoria = new SelectList(db.Categorias, "IdCategoria", "Nombre", producto.IdCategoria);
            ViewBag.IdLinea = new SelectList(db.Lineas, "IdLinea", "Nombre", producto.IdLinea);
            return View(producto);
        }

        // GET: Productoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Productos.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdCategoria = new SelectList(db.Categorias, "IdCategoria", "Nombre", producto.IdCategoria);
            ViewBag.IdLinea = new SelectList(db.Lineas, "IdLinea", "Nombre", producto.IdLinea);
            return View(producto);
        }

        // POST: Productoes/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdProducto,Nombre,Codigo,IdCategoria,IdLinea")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(producto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdCategoria = new SelectList(db.Categorias, "IdCategoria", "Nombre", producto.IdCategoria);
            ViewBag.IdLinea = new SelectList(db.Lineas, "IdLinea", "Nombre", producto.IdLinea);
            return View(producto);
        }

        // GET: Productoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Productos.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // POST: Productoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Producto producto = db.Productos.Find(id);
            db.Productos.Remove(producto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Natura/Views/Shared/_Layout.cshtml
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title> - Inventario</title>
@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/modernizr")



@Html.Partial("_MenuIz")

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Productos Natura", "Index", "Productoes", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Inicio", "Index", "Inventario")</li>
                @*<li>@Html.ActionLink("Acerca de", "About", "Home")</li>
        <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>*@
            </ul>
        </div>
    </div>
</div>
<br />
<br />
<br />
<div class="container body-content">
    @RenderBody()
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year -  Natura bien estar bien</p>

        <img src="~/Imagenes/nat.jpg" style="width:auto">
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)

Natura/Views/Shared/_MenuIz.cshtml
<link href="~/Scripts/CSS/_MenuIzquierdo.css" rel="Stylesheet" type="text/css" />

<div class="sidebar-container">
    <div class="sidebar-logo">
        Inventario Natura
    </div>
    <ul class="sidebar-navigation">
        <li class="header">Navegacion</li>
        @*<li>
            <a href="#">
                <i class="fa fa-home" aria-hidden="true"></i> Homepage
            </a>
        </li>
        <li>
            <a href="#">
                <i class="fa fa-tachometer" aria-hidden="true"></i> Dashboard
            </a>
        </li>*@
        <li>
            <a href="#">
                <i class="fa fa-home" aria-hidden="true"></i> Categorias
            </a>
        <li>
            <a href="#">
                <i class="fa fa-home" aria-hidden="true"></i> Lineas de productos
            </a>
        <li class="header">Otro Menu</li>
        <li>
            <a href="#">
                <i class="fa fa-users" aria-hidden="true"></i> Mis Datos
            </a>
        </li>
        @* <li>
            <a href="#">
                <i class="fa fa-cog" aria-hidden="true"></i> Settings
            </a>
        </li>
        <li>
            <a href="#">
                <i class="fa fa-info-circle" aria-hidden="true"></i> Information
            </a>
        </li>*@
    </ul>
</div>

<!--<div class="content-container">

    <div class="container-fluid">-->
<!-- Main component for a primary marketing message or call to action -->
<!--<div class="jumbotron">
            <h1>Navbar example</h1>

                <a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">View navbar docs &raquo;</a>

        </div>

    </div>
</div>-->
<br />
<br />
<br />
<br />
<br />